### PR TITLE
Fix to use ts-graphviz/setup-graphviz again on CI

### PR DESCRIPTION
**Pull request by kamiazya**
CI failed due to setup-graphviz behavior on macOS, so we no longer use ts-graphviz/setup-graphviz in PR #181.

In [ts-graphviz/setup-graphviz@v1.2.0](https://github.com/ts-graphviz/setup-graphviz/releases/tag/v1.2.0), this issue has been resolved and we are now using it again.

### CODE REVIEW

**Comment by kamiazya** [comment]
I have confirmed that Graphviz can be installed on macOS, but mypy has FAILED.

I know this is probably a different issue than this fix, but is there anything I can do to help?

**Comment by 2bndy5** [comment]
Looks like we'll have to fix the mypy issues separately. It is unfortunate to not get see the fix in action.

❤️ the quick response time and involvement on behalf of @ts-graphviz, thanks for this!

**Comment by kamiazya** [comment]
@2bndy5 We appreciate your report on the issue as well.

You can see that the fix has been applied in the JOB below.
The step with setup-graphviz is succesful and brew update is not running.

https://github.com/jbms/sphinx-immaterial/actions/runs/3853882835/jobs/6567324527

**Comment by kamiazya** [comment]
It is not a mypy issue, but may be affected by yesterday's release of Sphinx 6.1 series.

If mypy is right and the internals of the sphinix Python module have been changed, it may affect other users of this module, so it may be better to create a separate issue to deal with this issue.

I have no domain knowledge of this project or Sphinix, so I can't judge, but please refer to the following link.

- https://pypi.org/project/Sphinx/#history
- https://www.sphinx-doc.org/en/master/changes.html#release-6-1-0-released-jan-05-2023
- https://github.com/sphinx-doc/sphinx/compare/v6.0.1...v6.1.1

**Comment by jbms** [comment]
Thanks, can you change this to specify the action version by exact hash rather than version number?

**Comment by jbms** [comment]
The mypy failure appears to indicate a real incompatibility with 6.1 that we will need to fix.

**Comment by kamiazya** [comment]
@jbms Fixed the version specification of the action to be fixed by Git hash.

**Comment by jbms** [comment]
Mypy issue should be fixed by https://github.com/jbms/sphinx-immaterial/pull/202

**Comment by 2bndy5** [comment]
@kamiazya Can you rebase on latest main? #202 has been merged to main.

**Comment by kamiazya** [comment]
@2bndy5 Merged main.

I used GitHub's Fork Sync, so it was a merge commit, but the result will be the same :pray:

**Comment by jbms** [comment]
Thanks!

**Pull request merged**
